# Generated by Django 5.2.17 on 2026-09-12 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposer_role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=12)),
                ('kind', models.CharField(choices=[('reschedule', 'Reschedule'), ('rebook', 'Rebook')], max_length=12)),
                ('original_starts_at', models.DateTimeField()),
                ('original_status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], max_length=16)),
                ('original_duration_minutes', models.PositiveSmallIntegerField()),
                ('proposed_starts_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('superseded', 'Replaced by a newer proposal')], default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='care.appointment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('original_clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_proposal_snapshots', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_appointment_changes', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_appointment_proposals', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_proposal_responses', to=settings.AUTH_USER_MODEL)),
                ('resulting_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_rebooking_proposals', to='care.appointment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_proposals', to='care.messagethread')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['company', 'patient', 'status'], name='care_appoin_company_d5e8fb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('appointment',), name='one_pending_proposal_per_appointment')],
            },
        ),
    ]
