# Generated by Django 5.2.17 on 2026-09-12 14:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_appointment_proposal'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicaltask',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_clinicaltask_records', to='practices.patient'),
        ),
        migrations.CreateModel(
            name='RecordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_record_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalNoteTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='care.clinicalnote')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_assignments', to='care.recordtag')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clinical_notes', through='care.ClinicalNoteTagAssignment', to='care.recordtag'),
        ),
        migrations.CreateModel(
            name='TaskTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='care.recordtag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='care.clinicaltask')),
            ],
        ),
        migrations.AddField(
            model_name='clinicaltask',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='care.TaskTagAssignment', to='care.recordtag'),
        ),
        migrations.AddConstraint(
            model_name='recordtag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('company'), name='unique_record_tag_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnotetagassignment',
            constraint=models.UniqueConstraint(fields=('note', 'tag'), name='unique_clinical_note_tag_assignment'),
        ),
        migrations.AddConstraint(
            model_name='tasktagassignment',
            constraint=models.UniqueConstraint(fields=('task', 'tag'), name='unique_task_tag_assignment'),
        ),
    ]
