# Generated by Django 5.2.17 on 2026-09-12 16:05

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_lead_submission_key'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('leave', 'Leave'), ('sick', 'Sick leave'), ('other', 'Other')], default='leave', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_doctor_time_off', to=settings.AUTH_USER_MODEL)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_off_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
            ],
            options={
                'ordering': ('starts_at', 'pk'),
                'indexes': [models.Index(fields=['company', 'clinician', 'starts_at'], name='care_doctor_company_19d04e_idx'), models.Index(fields=['clinician', 'is_active', 'starts_at', 'ends_at'], name='care_doctor_clinici_8be65b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='doctor_time_off_positive'), models.CheckConstraint(condition=models.Q(('ends_at__lte', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(days=366))))), name='doctor_time_off_max_year'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('is_active', True)), models.Q(('cancelled_at__isnull', False), ('is_active', False)), _connector='OR'), name='doctor_time_off_cancel_state')],
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_working', models.BooleanField(default=False)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='working_patterns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
            ],
            options={
                'ordering': ('weekday',),
                'constraints': [models.UniqueConstraint(fields=('company', 'clinician', 'weekday'), name='unique_doctor_working_day'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='doctor_working_weekday_range'), models.CheckConstraint(condition=models.Q(models.Q(('ends_at__isnull', True), ('is_working', False), ('starts_at__isnull', True)), models.Q(('ends_at__gt', models.F('starts_at')), ('ends_at__isnull', False), ('is_working', True), ('starts_at__isnull', False)), _connector='OR'), name='doctor_working_hours_valid')],
            },
        ),
    ]
