# Generated by Django 5.2.17 on 2026-09-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_doctor_availability'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalencounter',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='signed_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_encounter', to='care.clinicalnote'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='signing_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_signing', to='care.clinicaltask'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='review_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_review_request', to='care.clinicaltask'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=160)),
                ('content', models.BinaryField()),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='care.labrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('size__gt', 0), ('size__lte', 5242880)), name='lab_result_size_limit')],
            },
        ),
    ]
