# Generated by Django 5.2.17 on 2026-09-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_clinical_workflows'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationproduct',
            name='allowance_group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='medicationproduct',
            name='is_compounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationproduct',
            name='requires_cold_chain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_shipments', to='care.treatmentauthorization'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispatch_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shipment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_profile', to='practices.patient')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Basket'), ('submitted', 'Requested'), ('accepted', 'Accepted for preparation'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_order', to='care.shipment')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='care.pharmacyorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='care.medicationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalProfileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='care.patientmedicalprofile')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-revision',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'revision'), name='unique_medical_profile_revision')],
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacyorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('patient',), name='one_patient_draft_basket'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='one_product_per_pharmacy_order'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lte', 100)), name='pharmacy_order_quantity_limit'),
        ),
    ]
