# Generated by Django 5.2.17 on 2026-09-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_patient_profiles_and_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationbatch',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('low', 'Low stock'), ('quarantined', 'Quarantined'), ('expired', 'Expired'), ('written_off', 'Written off')], default='available', max_length=16),
        ),
    ]
