# Generated by Django 5.2.17 on 2026-09-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_stock_write_off_state'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_enabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='communication_preference', to='practices.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('access', 'Request a copy of my information'), ('correction', 'Request a correction'), ('deletion', 'Request deletion review'), ('question', 'Privacy question')], max_length=16)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Submitted'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('declined', 'Declined with explanation')], default='open', max_length=16)),
                ('submission_key', models.UUIDField(editable=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PatientDataRequestReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Submitted'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('declined', 'Declined with explanation')], max_length=16)),
                ('submission_key', models.UUIDField(editable=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_request_replies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('data_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='care.patientdatarequest')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AdministrativeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Follow-up required'), ('done', 'Follow-up complete')], default='open', max_length=12)),
                ('next_contact_on', models.DateField(blank=True, null=True)),
                ('stage_before', models.CharField(blank=True, max_length=20)),
                ('stage_after', models.CharField(blank=True, max_length=20)),
                ('submission_key', models.UUIDField(editable=False, unique=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_administrative_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='care.lead')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='care.patientsubscription')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('lead__isnull', False), ('subscription__isnull', True)), models.Q(('lead__isnull', True), ('subscription__isnull', False)), _connector='OR'), name='follow_up_has_one_target')],
            },
        ),
        migrations.CreateModel(
            name='DoctorActivityStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('counts', models.JSONField(default=dict)),
                ('rates', models.JSONField(default=dict)),
                ('source_ids', models.JSONField(default=dict)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_activity_statements', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_statements', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_activity_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', 'doctor_id'),
                'constraints': [models.UniqueConstraint(fields=('company', 'doctor', 'period_start', 'period_end'), name='unique_doctor_activity_statement')],
            },
        ),
    ]
