# Generated by Django 5.2.17 on 2026-09-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0009_administrative_followups_and_account_requests'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationReviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_on', models.DateField()),
                ('authorization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_reminder', to='care.treatmentauthorization')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_reminder', to='care.clinicaltask')),
            ],
            options={
                'ordering': ('due_on', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CompoundingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Awaiting doctor review'), ('ready', 'Reviewed, ready for manual submission'), ('submitted', 'Manual submission recorded'), ('cancelled', 'Cancelled before submission')], default='draft', max_length=16)),
                ('preparation_note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('submission_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compounding_records', to='care.treatmentauthorization')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compounding_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_compounding_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compounding_record', to='care.clinicaltask')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['company', 'clinician', 'status'], name='care_compou_company_52ccb0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='compounding_revision_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='ready_compounding_has_review'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), _negated=True), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('submitted_at__isnull', False), models.Q(('external_reference', ''), _negated=True)), _connector='OR'), name='submitted_compounding_has_record')],
            },
        ),
    ]
