# Generated by Django 5.2.17 on 2026-10-03 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing conversations belong to the staff who wrote in them, else the patient's clinician."""
    MessageThread = apps.get_model('care', 'MessageThread')
    PatientMessage = apps.get_model('care', 'PatientMessage')
    Participant = apps.get_model('care', 'MessageThreadParticipant')
    Assignment = apps.get_model('care', 'ClinicianAssignment')
    AuditEvent = apps.get_model('care', 'AuditEvent')
    Patient = apps.get_model('practices', 'Patient')
    for thread in MessageThread.objects.select_related('patient').iterator():
        patient_user = thread.patient.user_id
        staff = list(PatientMessage.objects.filter(thread=thread, sender__isnull=False).exclude(sender_id=patient_user)
                     .order_by('created_at', 'pk').values_list('sender_id', flat=True))
        if thread.opened_by_id and thread.opened_by_id != patient_user:
            staff.insert(0, thread.opened_by_id)
        if not staff and thread.patient.assigned_doctor_id:
            staff = [thread.patient.assigned_doctor_id]
        for user_id in dict.fromkeys(staff):
            Participant.objects.get_or_create(company_id=thread.company_id, thread=thread, user_id=user_id)
    for patient in Patient.objects.all().iterator():
        past = set()
        for event in AuditEvent.objects.filter(patient=patient, action='patient.doctor_assigned').order_by('created_at'):
            for key in ('previous_doctor_id', 'doctor_id'):
                if event.metadata.get(key):
                    past.add((event.metadata[key], event.created_at))
        for clinician_id, when in sorted(past, key=lambda item: item[1]):
            if clinician_id != patient.assigned_doctor_id and not Assignment.objects.filter(patient=patient, clinician_id=clinician_id).exists():
                Assignment.objects.create(company_id=patient.company_id, patient=patient, clinician_id=clinician_id, ended_at=when)
        if patient.assigned_doctor_id:
            Assignment.objects.create(company_id=patient.company_id, patient=patient, clinician_id=patient.assigned_doctor_id)


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0010_compounding_and_review_reminders"),
        ("practices", "0003_companymembership_clinician_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageThreadParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="practices.company",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_links",
                        to="care.messagethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_thread_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.AddField(
            model_name="messagethread",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="message_threads",
                through="care.MessageThreadParticipant",
                through_fields=("thread", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClinicianAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinician_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="practices.company",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_records",
                        to="practices.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("patient",),
                        name="one_open_clinician_assignment_per_patient",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messagethreadparticipant",
            constraint=models.UniqueConstraint(
                fields=("thread", "user"), name="one_participant_link_per_thread"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
