# Generated by Django 5.2.17 on 2026-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0012_team_messaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesettings",
            name="store_view_log",
            field=models.BooleanField(
                default=False,
                help_text="Also record when people view, download or export records. Stored for the practice audit only and never shown in the app.",
                verbose_name="Store view log on database",
            ),
        ),
    ]
