# Generated by Django 5.2.17 on 2026-10-02 20:35

from django.conf import settings
from django.db import migrations, models


def existing_doctors_are_doctors(apps, schema_editor):
    # Practice admins and Super Admins start as None; a Super Admin who also
    # treats patients is given a type explicitly on their staff page.
    apps.get_model('practices', 'CompanyMembership').objects.filter(role='doctor').update(clinician_type='doctor')


class Migration(migrations.Migration):

    dependencies = [
        ("practices", "0002_patient_assigned_doctor_patient_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companymembership",
            name="clinician_type",
            field=models.CharField(
                blank=True,
                choices=[("doctor", "Doctor"), ("dietitian", "Dietitian")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Clinician"),
                    ("practice_admin", "Practice administrator"),
                    ("super_admin", "Super admin"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("clinician_type__in", ("doctor", "dietitian")),
                    ("role", "practice_admin"),
                    _negated=True,
                ),
                name="practice_admin_is_not_a_clinician",
            ),
        ),
        migrations.RunPython(existing_doctors_are_doctors, migrations.RunPython.noop),
    ]
