"""Meridian's clinical administration theme (all assets served locally)."""

JAZZMIN_SETTINGS = {
    'site_title': 'Meridian | Practice administration',
    'site_header': 'Meridian Health',
    'site_brand': 'Practice administration',
    'site_logo': 'images/meridian-logo.png',
    'login_logo': 'images/meridian-logo.png',
    'site_logo_classes': 'meridian-brand-image',
    'site_icon': 'images/meridian-admin-icon.svg',
    'welcome_sign': 'Your practice, in focus.',
    'copyright': 'Meridian Health',
    'show_sidebar': True,
    'navigation_expanded': False,
    'show_ui_builder': False,
    'show_theme_chooser': False,
    'use_google_fonts_cdn': False,
    'custom_css': 'css/meridian_admin.css',
    'custom_js': 'js/meridian_admin.js',
    'topmenu_links': [
        {'name': 'Overview', 'url': 'admin:index'},
        {'name': 'Meridian website', 'url': '/'},
    ],
    # Model links are supplied by Django's permission-aware app list. In
    # particular, do not surface Company management in single-practice mode.
    'order_with_respect_to': [
        'practices', 'practices.Patient', 'practices.CompanyMembership',
        'care', 'care.Appointment', 'care.ClinicalTask', 'care.LabRequest',
        'care.PatientSubscription', 'care.Invoice', 'care.Shipment',
        'accounts', 'video', 'auth',
    ],
    'icons': {
        'practices': 'fas fa-clinic-medical',
        'practices.Patient': 'fas fa-user-friends',
        'practices.CompanyMembership': 'fas fa-user-shield',
        'practices.Company': 'fas fa-hospital',
        'care': 'fas fa-heartbeat',
        'care.Appointment': 'far fa-calendar-check',
        'care.ClinicalTask': 'fas fa-clipboard-check',
        'care.LabRequest': 'fas fa-vial',
        'care.LabResult': 'fas fa-microscope',
        'care.PatientSubscription': 'fas fa-sync-alt',
        'care.Invoice': 'fas fa-file-invoice',
        'care.Payment': 'fas fa-credit-card',
        'care.Shipment': 'fas fa-shipping-fast',
        'care.Lead': 'fas fa-user-plus',
        'care.ClinicalEncounter': 'fas fa-stethoscope',
        'care.MedicationProduct': 'fas fa-capsules',
        'care.AuditEvent': 'fas fa-history',
        'accounts': 'fas fa-users-cog',
        'accounts.User': 'fas fa-user-circle',
        'video': 'fas fa-video',
        'video.CallSession': 'fas fa-video',
        'auth': 'fas fa-shield-alt',
        'auth.Group': 'fas fa-users',
    },
    'default_icon_parents': 'fas fa-layer-group',
    'default_icon_children': 'far fa-circle',
    'related_modal_active': False,
    'changeform_format': 'horizontal_tabs',
    'language_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'default',
    'default_theme_mode': 'light',
    'navbar_fixed': True,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'navbar': 'navbar-white navbar-light',
    'accent': 'accent-teal',
    'sidebar_nav_small_text': True,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'button_classes': {
        'primary': 'btn-primary', 'secondary': 'btn-outline-secondary',
        'info': 'btn-outline-primary', 'warning': 'btn-warning',
        'danger': 'btn-danger', 'success': 'btn-success',
    },
}
