from django.urls import include, path

from . import appointment_views, availability_views, clinical_views, intake_views, lead_views, message_management_views, patient_views, staff_views, task_views, views
from .patient_workspace import PatientWorkspaceView

app_name = 'portal'

urlpatterns = [
    path('', include('portal.privacy_urls')),
    path('messages/<int:pk>/manage/', message_management_views.ConversationManagementView.as_view(), name='conversation-manage'),
    path('', include('portal.appointment_detail_urls')),
    path('', include('portal.compounding_urls')),
    path('', include('portal.reporting_urls')),
    path('', include('portal.record_urls')),
    path('', include('portal.followup_urls')),
    path('', include('practices.management_urls')),
    path('', include('portal.treatment_urls')),
    path('', include('portal.patient_care_urls')),
    path('', include('portal.operations_urls')),
    path('questionnaire/', intake_views.QuestionnaireView.as_view(), name='questionnaire'),
    path('questionnaire/result/', intake_views.QuestionnaireResultView.as_view(), name='questionnaire-result'),
    path('questionnaire/checkout/', intake_views.QuestionnaireCheckoutView.as_view(), name='questionnaire-checkout'),
    path('leads/', lead_views.LeadListView.as_view(), name='staff-leads'),
    path('leads/<int:pk>/', lead_views.LeadDetailView.as_view(), name='lead-detail'),
    path('desktop/', views.DesktopDashboardView.as_view(), name='desktop-dashboard'),
    path('mobile/', views.MobileDashboardView.as_view(), name='mobile-dashboard'),
    path('messages/', views.StaffInboxView.as_view(), name='staff-inbox'),
    path('tasks/', staff_views.StaffTaskListView.as_view(), name='staff-tasks'),
    path('tasks/new/', task_views.TaskEditorView.as_view(), name='task-create'),
    path('tasks/<int:pk>/', task_views.TaskEditorView.as_view(), name='task-edit'),
    path('patients/', staff_views.PatientListView.as_view(), name='patient-list'),
    path('consultations/', clinical_views.ConsultationListView.as_view(), name='clinical-consultations'),
    path('consultations/<int:pk>/', clinical_views.ConsultationEditorView.as_view(), name='clinical-consultation-detail'),
    path('patients/<int:patient_pk>/consultations/new/', clinical_views.ConsultationEditorView.as_view(), name='clinical-consultation-create'),
    path('blood-tests/', clinical_views.LabListView.as_view(), name='clinical-labs'),
    path('blood-tests/<int:pk>/', clinical_views.LabDetailView.as_view(), name='clinical-lab-detail'),
    path('blood-tests/<int:pk>/report/', clinical_views.LabResultDownloadView.as_view(), name='clinical-lab-result-download'),
    path('patients/<int:patient_pk>/blood-tests/new/', clinical_views.LabCreateView.as_view(), name='clinical-lab-create'),
    path('schedule/', staff_views.StaffScheduleView.as_view(), name='staff-schedule'),
    path('schedule/working-pattern/', availability_views.WorkingPatternUpdateView.as_view(), name='availability-working-pattern'),
    path('schedule/time-off/', availability_views.TimeOffCreateView.as_view(), name='availability-time-off-create'),
    path('schedule/time-off/<int:pk>/cancel/', availability_views.TimeOffCancelView.as_view(), name='availability-time-off-cancel'),
    path('companies/<slug:slug>/activate/', views.ActivateCompanyView.as_view(), name='activate-company'),
    path('patient/', views.PatientDashboardView.as_view(), name='patient-dashboard'),
    path('patient/appointments/', patient_views.PatientAppointmentsView.as_view(), name='patient-appointments'),
    path('patient/progress/', patient_views.PatientProgressView.as_view(), name='patient-progress'),
    path('patient/account/', patient_views.PatientAccountView.as_view(), name='patient-account'),
    path('patient/blood-tests/', clinical_views.PatientLabListView.as_view(), name='patient-labs'),
    path('patient/blood-tests/<int:pk>/', clinical_views.PatientLabDetailView.as_view(), name='patient-lab-detail'),
    path('patient/blood-tests/<int:pk>/report/', clinical_views.PatientLabResultDownloadView.as_view(), name='patient-lab-result-download'),
    path('patient/companies/<slug:slug>/activate/', views.ActivatePatientCompanyView.as_view(), name='activate-patient-company'),
    path('patient/weight/', views.PatientWeightAddView.as_view(), name='patient-weight-add'),
    path('patient/messages/<int:pk>/', views.PatientMessageCreateView.as_view(), name='patient-message-create'),
    path('patient/messages/', patient_views.PatientMessagesView.as_view(), name='patient-messages'),
    path('patient/messages/new/', views.PatientThreadCreateView.as_view(), name='patient-thread-create'),
    path('patients/<int:pk>/', PatientWorkspaceView.as_view(), name='patient-detail'),
    path('patients/<int:patient_pk>/tasks/', views.PatientTaskCreateView.as_view(), name='patient-task-create'),
    path('patients/<int:patient_pk>/appointments/', views.PatientAppointmentCreateView.as_view(), name='patient-appointment-create'),
    path('patients/<int:patient_pk>/notes/', views.PatientNoteCreateView.as_view(), name='patient-note-create'),
    path('patients/<int:patient_pk>/notes/<int:pk>/tags/', task_views.ClinicalNoteTagsView.as_view(), name='patient-note-tags'),
    path('patients/<int:patient_pk>/messages/', views.StaffThreadCreateView.as_view(), name='staff-thread-create'),
    path('tasks/<int:pk>/complete/', views.TaskCompleteView.as_view(), name='task-complete'),
    path('messages/<int:pk>/', views.StaffMessageCreateView.as_view(), name='staff-message-create'),
    path('messages/<int:pk>/appointment-proposals/', appointment_views.StaffAppointmentProposeView.as_view(), name='staff-appointment-propose'),
    path('appointment-proposals/<int:pk>/respond/', appointment_views.StaffAppointmentRespondView.as_view(), name='staff-appointment-respond'),
    path('patient/messages/<int:pk>/appointment-proposals/', appointment_views.PatientAppointmentProposeView.as_view(), name='patient-appointment-propose'),
    path('patient/appointment-proposals/<int:pk>/respond/', appointment_views.PatientAppointmentRespondView.as_view(), name='patient-appointment-respond'),
]
