# Generated by Django 5.2.17 on 2026-09-12 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0010_compounding_and_review_reminders'),
        ('practices', '0002_patient_assigned_doctor_patient_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('lease_expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('presence_revision', models.PositiveBigIntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_sessions', to='care.appointment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_video_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_sessions', to='practices.patient')),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_key', models.UUIDField(editable=False, unique=True)),
                ('joined_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('lease_expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='practices.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='video.callsession')),
            ],
            options={
                'ordering': ('joined_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='video_session_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.CheckConstraint(condition=models.Q(('lease_expires_at__gte', models.F('started_at'))), name='video_session_valid_lease'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('joined_at')), _connector='OR'), name='video_participant_end_after_join'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('lease_expires_at__gte', models.F('joined_at'))), name='video_participant_valid_lease'),
        ),
    ]
